language: node_js
node_js:
- 5.10.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: 199.58.81.155
before_install:
- openssl aes-256-cbc -K $encrypted_7ed872643f93_key -iv $encrypted_7ed872643f93_iv
  -in deploy-key-malawi.enc -out deploy-key-malawi -d
- chmod 600 ~/.ssh/config
- chmod 600 deploy-key-malawi
- mv deploy-key-malawi ~/.ssh/id_rsa
- rm deploy-key-malawi.enc
- echo -e "Host 199.58.81.155\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
- bash scripts/install.sh
before_script:
- bash scripts/install.sh
- npm install grunt-cli -g
script:
- bash scripts/build.sh
after_success:
- bash scripts/deploy.sh
branches:
  only:
  - master
